---
desc: "Swifty DEMO functions"
files:
        - name: "Hello world"
          path: "functions/golang/helloworld.go"
          lang: "golang"
          desc: "A hello-world example"
        - name: "Telegram chatbot on Python"
          path: "functions/python/telegram_bot.go"
          lang: "python"
          desc: "Simple chatbpt for Telegram written on Python."
